
version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: nestjs_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: nestjs_db
      MYSQL_USER: nestjs_user
      MYSQL_PASSWORD: nestjs_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - nestjs_network

volumes:
  mysql_data:

networks:
  nestjs_network:
    driver: bridge